using OneWare.Essentials.PackageManager;

namespace OneWare.CologneChip.Services;

public sealed class CologneChipConstantService
{

    private static readonly Lazy<CologneChipConstantService> _instance = new Lazy<CologneChipConstantService>(() => new CologneChipConstantService());
    private CologneChipConstantService() {}

    public static CologneChipConstantService Instance => _instance.Value;

    public static string CologneChipShortTermModeKey => "cologneChipProgrammerShortTermMode";
    public static string CologneChipLongTermModeKey => "cologneChipProgrammerLongTermMode";
    public static string CologneChipTypeKey => "cologneChipProgrammerType";
    
    public static string CologneChipSettingsIgnoreGuiKey => "cologneChip_IgnoreGui";
    public static string CologneChipSettingsIgnoreSynthExitCode => "cologneChip_SynthExitCode";

    public static string CologneChipSettingsUseWsl => "cologneChip_UseWSL";
    
    public static string CologneChipDefaultConstraintFile => "project.ccf";

    public const string CcfTemplate = @"#
# #####  Important ##### 
# Currently, the pin constraints must be added manually in this file
# #####  #####  ##### 
# This file is automatically generated by OneWare Cologne Chip Extenstion.
#
# Syntax:
# NET ""<pin-name>"" Loc = ""<pin-location>"" | <opt.-constraints>;
#
# Backward compatible legacy syntax:
# <pin-direction> ""<pin-name>"" Loc = ""<pin-location>"" | <opt.-constraints>;
#
# Additional constraints can be appended using the pipe symbol.
# Files are read line by line. Text after the hash symbol is ignored.
#
# Available legacy pin directions:
#
# Pin_in
#   defines an input pin
# Pin_out
#   defines an output pin
# Pin_triout
#   defines a tristate output pin
# Pin_inout
#   defines a bidirectional pin
#
# Available pin constraints:
#
# SCHMITT_TRIGGER={true,false}
#   enables or disables schmitt trigger (hysteresis) option
# PULLUP={true,false}
#   enables or disables I/O pullup resistor of nominal 50kOhm
# PULLDOWN={true,false}
#   enables or disables I/O pulldown resistor of nominal 50kOhm
# KEEPER={true,false}
#   enables or disables I/O keeper option
# SLEW={slow,fast}
#   sets slew rate to slow or fast
# DRIVE={3,6,9,12}
#   sets output drive strength to 3mA..12mA
# DELAY_OBF={0..15}
#   adds an additional delay of n * nominal 50ps to output signal
# DELAY_IBF={0..15}
#   adds an additional delay of n * nominal 50ps to input signal
# FF_IBF={true,false}
#   enables or disables placing of FF in input buffer, if possible
# FF_OBF={true,false}
#   enables or disables placing of FF in output buffer, if possible
# LVDS_BOOST={true,false}
#   enables increased LVDS output current of 6.4mA (default: 3.2mA)
# LVDS_RTERM={true,false}
#   enables on-chip LVDS termination resistor of nominal 100Ohm, in input mode only
#
# Global IO constraints can be set with the default_GPIO statement. It can be
# overwritten by individual settings for specific GPIOs, e.g.:
#   default_GPIO | DRIVE=3; # sets all output strengths to 3mA, unless overwritten";

    
    // Weitere Konstanten können hier hinzugefügt werden
    public string GetBuildPath(string path)
    {
        if (string.IsNullOrEmpty(path))
            return "./build/";
        return $"{path.TrimEnd('/')}/build/";
    }
    
    public const string CCPathSetting = "CCCadSuite_Path";
    
    public static readonly Package CologneChipPackage = new()
    {
        Category = "Binaries",
        Id = "colognechip",
        Type = "NativeTool",
        Name = "CologneChip Tools",
        Description = "Open Source FPGA Tools",
        License = "ISC",
        IconUrl =
            "https://avatars.githubusercontent.com/u/35169771?s=48&v=4",
        Links =
        [
            new PackageLink
            {
                Name = "GitHub",
                Url = "https://www.colognechip.com/docs/ug1002-toolchain-install-latest.pdf"
            }
        ],
        Tabs =
        [
            new PackageTab()
            {
                Title = "Readme",
                ContentUrl = "https://raw.githubusercontent.com/HendrikMennen/oss-cad-suite-build/main/README.md"
            },
            new PackageTab
            {
                Title = "License",
                ContentUrl = "https://raw.githubusercontent.com/YosysHQ/oss-cad-suite-build/main/COPYING"
            }
        ],
        Versions =
        [
            new PackageVersion
            {
                Version = "latest",
                Targets =
                [
                    new PackageTarget
                    {
                        Target = "win-x64",
                        Url =
                            "https://colognechip.com/downloads/cc-toolchain-win.zip",
                        AutoSetting =
                        [
                            new PackageAutoSetting
                            {
                                RelativePath = "cologne-chip",
                                SettingKey = CCPathSetting
                            }
                        ]
                    },
                    new PackageTarget
                    {
                        Target = "linux-x64",
                        Url =
                            "https://colognechip.com/downloads/cc-toolchain-linux.zip",
                        AutoSetting =
                        [
                            new PackageAutoSetting
                            {
                                RelativePath = "cologne-chip",
                                SettingKey = CCPathSetting
                            }
                        ]
                    },
                    new PackageTarget
                    {
                        Target = "osx-x64",
                        Url =
                            "https://colognechip.com/downloads/cc-toolchain-linux.zip",
                        AutoSetting =
                        [
                            new PackageAutoSetting
                            {
                                RelativePath = "cologne-chip",
                                SettingKey = CCPathSetting
                            }
                        ]
                    },
                    new PackageTarget
                    {
                        Target = "osx-arm64",
                        Url =
                            "https://colognechip.com/downloads/cc-toolchain-linux.zip",
                        AutoSetting =
                        [
                            new PackageAutoSetting
                            {
                                RelativePath = "cologne-chip",
                                SettingKey = CCPathSetting
                            }
                        ]
                    }
                ]
            },
        ]
    };
}